/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RideRouteImport } from './routes/ride'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DriverFoundRouteImport } from './routes/driver-found'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderVehicleRouteImport } from './routes/order.vehicle'
import { Route as OrderShareRouteImport } from './routes/order.share'
import { Route as OrderPriceRouteImport } from './routes/order.price'
import { Route as HistoryRideIdRouteImport } from './routes/history.$rideId'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverFoundRoute = DriverFoundRouteImport.update({
  id: '/driver-found',
  path: '/driver-found',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderVehicleRoute = OrderVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => OrderRoute,
} as any)
const OrderShareRoute = OrderShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => OrderRoute,
} as any)
const OrderPriceRoute = OrderPriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => OrderRoute,
} as any)
const HistoryRideIdRoute = HistoryRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => HistoryRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/order': typeof OrderRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/auth/otp': typeof AuthOtpRoute
  '/history/$rideId': typeof HistoryRideIdRoute
  '/order/price': typeof OrderPriceRoute
  '/order/share': typeof OrderShareRoute
  '/order/vehicle': typeof OrderVehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/order': typeof OrderRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/auth/otp': typeof AuthOtpRoute
  '/history/$rideId': typeof HistoryRideIdRoute
  '/order/price': typeof OrderPriceRoute
  '/order/share': typeof OrderShareRoute
  '/order/vehicle': typeof OrderVehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/completed': typeof CompletedRoute
  '/driver-found': typeof DriverFoundRoute
  '/history': typeof HistoryRouteWithChildren
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/order': typeof OrderRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/ride': typeof RideRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/auth/otp': typeof AuthOtpRoute
  '/history/$rideId': typeof HistoryRideIdRoute
  '/order/price': typeof OrderPriceRoute
  '/order/share': typeof OrderShareRoute
  '/order/vehicle': typeof OrderVehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/order'
    | '/payment'
    | '/profile'
    | '/ride'
    | '/settings'
    | '/tracking'
    | '/auth/otp'
    | '/history/$rideId'
    | '/order/price'
    | '/order/share'
    | '/order/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/order'
    | '/payment'
    | '/profile'
    | '/ride'
    | '/settings'
    | '/tracking'
    | '/auth/otp'
    | '/history/$rideId'
    | '/order/price'
    | '/order/share'
    | '/order/vehicle'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/booking'
    | '/completed'
    | '/driver-found'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/order'
    | '/payment'
    | '/profile'
    | '/ride'
    | '/settings'
    | '/tracking'
    | '/auth/otp'
    | '/history/$rideId'
    | '/order/price'
    | '/order/share'
    | '/order/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BookingRoute: typeof BookingRoute
  CompletedRoute: typeof CompletedRoute
  DriverFoundRoute: typeof DriverFoundRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  OrderRoute: typeof OrderRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RideRoute: typeof RideRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-found': {
      id: '/driver-found'
      path: '/driver-found'
      fullPath: '/driver-found'
      preLoaderRoute: typeof DriverFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/vehicle': {
      id: '/order/vehicle'
      path: '/vehicle'
      fullPath: '/order/vehicle'
      preLoaderRoute: typeof OrderVehicleRouteImport
      parentRoute: typeof OrderRoute
    }
    '/order/share': {
      id: '/order/share'
      path: '/share'
      fullPath: '/order/share'
      preLoaderRoute: typeof OrderShareRouteImport
      parentRoute: typeof OrderRoute
    }
    '/order/price': {
      id: '/order/price'
      path: '/price'
      fullPath: '/order/price'
      preLoaderRoute: typeof OrderPriceRouteImport
      parentRoute: typeof OrderRoute
    }
    '/history/$rideId': {
      id: '/history/$rideId'
      path: '/$rideId'
      fullPath: '/history/$rideId'
      preLoaderRoute: typeof HistoryRideIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthOtpRoute: typeof AuthOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOtpRoute: AuthOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HistoryRouteChildren {
  HistoryRideIdRoute: typeof HistoryRideIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryRideIdRoute: HistoryRideIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface OrderRouteChildren {
  OrderPriceRoute: typeof OrderPriceRoute
  OrderShareRoute: typeof OrderShareRoute
  OrderVehicleRoute: typeof OrderVehicleRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderPriceRoute: OrderPriceRoute,
  OrderShareRoute: OrderShareRoute,
  OrderVehicleRoute: OrderVehicleRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BookingRoute: BookingRoute,
  CompletedRoute: CompletedRoute,
  DriverFoundRoute: DriverFoundRoute,
  HistoryRoute: HistoryRouteWithChildren,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  OrderRoute: OrderRouteWithChildren,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RideRoute: RideRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
